In [1]:
# 1. 사전 환경 준비
!pip install shap

error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
    xyz, where xyz is the package you are trying to
    install.

    If you wish to install a Python library that isn't in Homebrew,
    use a virtual environment:

    python3 -m venv path/to/venv
    source path/to/venv/bin/activate
    python3 -m pip install xyz

    If you wish to install a Python application that isn't in Homebrew,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. You can install pipx with

    brew install pipx

    You may restore the old behavior of pip by passing
    the '--break-system-packages' flag to pip, or by adding
    'break-system-packages = true' to your pip.conf file. The latter
    will permanently disable this error.

    If you disable this error, we STRONGLY recommend that you additionally
    pass the '--user' flag to pip, or set 'user = true' in your pip.conf
    file. Failure to do this can result in a broken Homebrew installation.

    Read more about this behavior here: <https://peps.python.org/pep-0668/>

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

### Import & Data Load

In [2]:
# Import & Data Load

In [3]:
import numpy as np
import pandas as pd
from lightgbm import LGBMRegressor
from sklearn.preprocessing import LabelEncoder

In [4]:
import os

# 실행 경로와 상관없이 데이터를 로드할 수 있도록 상대 경로 자동 조정
data_dir = "." if os.path.exists("train.csv") else "../.."
train = pd.read_csv(os.path.join(data_dir, "train.csv"))
test = pd.read_csv(os.path.join(data_dir, "test.csv"))

In [5]:
train.head(5)

,ID,gender,age,height,weight,cholesterol,systolic_blood_pressure,diastolic_blood_pressure,glucose,bone_density,activity,smoke_status,medical_history,family_medical_history,sleep_pattern,edu_level,mean_working,stress_score
0,TRAIN_0000,F,72,161.49,58.47,279.84,165,100,143.35,0.87,moderate,ex-smoker,high blood pressure,diabetes,sleep difficulty,bachelors degree,NaN,0.63
1,TRAIN_0001,M,88,179.87,77.60,257.37,178,111,146.94,0.07,moderate,ex-smoker,NaN,diabetes,normal,graduate degree,NaN,0.83
2,TRAIN_0002,M,47,182.47,89.93,226.66,134,95,142.61,1.18,light,ex-smoker,NaN,NaN,normal,high school diploma,9.0,0.70
3,TRAIN_0003,M,69,185.78,68.63,206.74,158,92,137.26,0.48,intense,ex-smoker,high blood pressure,NaN,oversleeping,graduate degree,NaN,0.17
4,TRAIN_0004,F,81,164.63,71.53,255.92,171,116,129.37,0.34,moderate,ex-smoker,diabetes,diabetes,sleep difficulty,bachelors degree,NaN,0.36

### Check Data

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        3000 non-null   object
 1   gender                    3000 non-null   object
 2   age                       3000 non-null   int64
 3   height                    3000 non-null   float64
 4   weight                    3000 non-null   float64
 5   cholesterol               3000 non-null   float64
 6   systolic_blood_pressure   3000 non-null   int64
 7   diastolic_blood_pressure  3000 non-null   int64
 8   glucose                   3000 non-null   float64
 9   bone_density              3000 non-null   float64
 10  activity                  3000 non-null   object
 11  smoke_status              3000 non-null   object
 12  medical_history           1711 non-null   object
 13  family_medical_history    1514 non-null   object
 14  sleep_pattern             3000 non-null   object
 15  edu_level                 2393 non-null   object
 16  mean_working              1968 non-null   float64
 17  stress_score              3000 non-null   float64
dtypes: float64(7), int64(3), object(8)
memory usage: 422.0+ KB

In [7]:
train.isnull().sum()

ID                             0
gender                         0
age                            0
height                         0
weight                         0
cholesterol                    0
systolic_blood_pressure        0
diastolic_blood_pressure       0
glucose                        0
bone_density                   0
activity                       0
smoke_status                   0
medical_history             1289
family_medical_history      1486
sleep_pattern                  0
edu_level                    607
mean_working                1032
stress_score                   0
dtype: int64

In [8]:
# 결측값 있는 칼럼(column) 확인
missing_columns_train = train.columns[train.isnull().sum() > 0]
missing_columns_train

Index(['medical_history', 'family_medical_history', 'edu_level',
       'mean_working'],
      dtype='object')

In [9]:
train[missing_columns_train].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   medical_history         1711 non-null   object
 1   family_medical_history  1514 non-null   object
 2   edu_level               2393 non-null   object
 3   mean_working            1968 non-null   float64
dtypes: float64(1), object(3)
memory usage: 93.9+ KB

In [10]:
# ==========================================
# 1. 통합 결측치 처리 및 3D Cascade 대치
# ==========================================
for df in [train, test]:
    df["medical_history"] = df["medical_history"].fillna("none")
    df["family_medical_history"] = df["family_medical_history"].fillna("none")
    df["edu_level"] = df["edu_level"].fillna("Unknown")
    df["is_working_missing"] = df["mean_working"].isnull().astype(int)

# Ordinal Encoding 매핑 사전 선언
edu_map = {
    "Unknown": 0,
    "high school diploma": 1,
    "bachelors degree": 2,
    "graduate degree": 3,
}
activity_map = {"light": 1, "moderate": 2, "intense": 3}
for df in [train, test]:
    df["edu_level_encoded"] = df["edu_level"].map(edu_map)
    df["activity_encoded"] = df["activity"].map(activity_map)

# 3D 세분화 결측 대치 그룹
train["age_group"] = (train["age"] // 10) * 10
test["age_group"] = (test["age"] // 10) * 10

group_cols_3d = ["age_group", "edu_level_encoded", "activity_encoded"]
group_cols_2d = ["age_group", "edu_level_encoded"]

medians_3d = train.groupby(group_cols_3d)["mean_working"].median()
medians_2d = train.groupby(group_cols_2d)["mean_working"].median()
overall_median = train["mean_working"].median()


def impute_working(row, medians_3d, medians_2d, overall_median):
    if not pd.isnull(row["mean_working"]):
        return row["mean_working"]
    key_3d = (row["age_group"], row["edu_level_encoded"], row["activity_encoded"])
    if key_3d in medians_3d and not pd.isnull(medians_3d[key_3d]):
        return medians_3d[key_3d]
    key_2d = (row["age_group"], row["edu_level_encoded"])
    if key_2d in medians_2d and not pd.isnull(medians_2d[key_2d]):
        return medians_2d[key_2d]
    return overall_median


train["mean_working"] = train.apply(
    lambda r: impute_working(r, medians_3d, medians_2d, overall_median), axis=1
)
test["mean_working"] = test.apply(
    lambda r: impute_working(r, medians_3d, medians_2d, overall_median), axis=1
)

train.drop("age_group", axis=1, inplace=True)
test.drop("age_group", axis=1, inplace=True)

# ==========================================
# 2. 피처 정제 및 bmi 복원 (Ponderal Index, Hypertension, Risk Score 등 구간화/상관 변수 전면 삭제)
# ==========================================
for df in [train, test]:
    # 의학 표준 BMI 복원
    df["bmi"] = df["weight"] / ((df["height"] / 100) ** 2)

    # 비선형 생체 지표 도메인 결합
    df["pulse_pressure"] = (
        df["systolic_blood_pressure"] - df["diastolic_blood_pressure"]
    )
    df["map"] = (df["systolic_blood_pressure"] + 2 * df["diastolic_blood_pressure"]) / 3
    df["glucose_cholesterol_ratio"] = df["glucose"] / (df["cholesterol"] + 1)
    df["overwork_and_poor_sleep"] = (
        (df["mean_working"] >= 12) & (df["sleep_pattern"] == "sleep difficulty")
    ).astype(int)
    df["vascular_bone_risk"] = (
        (df["bone_density"] <= -1.0) & (df["pulse_pressure"] > 80)
    ).astype(int)

# 복합 질환(medical_history) 동적 이진화 플래그 생성 (오직 train 기준으로만 질환 Vocabulary 추출 - Leakage 완전 차단)
diseases = set()
for col in ["medical_history", "family_medical_history"]:
    for val in train[col].dropna().unique():
        for d in val.split(","):
            diseases.add(d.strip())
diseases.discard("none")
diseases = sorted(list(diseases))

for col, prefix in [("medical_history", "med"), ("family_medical_history", "fam")]:
    for disease in diseases:
        feat_name = f'{prefix}_{disease.lower().replace(" ", "_")}'
        train[feat_name] = train[col].apply(
            lambda x: 1 if disease in [d.strip() for d in x.split(",")] else 0
        )
        test[feat_name] = test[col].apply(
            lambda x: 1 if disease in [d.strip() for d in x.split(",")] else 0
        )

# 사용이 끝난 원본 문자열 컬럼 일괄 삭제
drop_cols = ["edu_level", "activity", "medical_history", "family_medical_history"]
train.drop(columns=drop_cols, inplace=True)
test.drop(columns=drop_cols, inplace=True)

In [11]:
# 순서형 인코딩된 컬럼을 제외한 순수 범주형 데이터 변환 및 타입 지정
categorical_cols = ["gender", "smoke_status", "sleep_pattern"]

for col in categorical_cols:
    train[col] = train[col].astype("category")
    test[col] = test[col].astype("category")

In [12]:
x_train = train.drop(["ID", "stress_score"], axis=1)
y_train = train["stress_score"]
x_test = test.drop("ID", axis=1)

In [13]:
import shap
import lightgbm as lgb
import matplotlib.pyplot as plt
from sklearn.preprocessing import RobustScaler

print("Calculating SHAP values for baseline model feature selection...")
x_train_temp = x_train.copy()
scaler_g = RobustScaler()
scaler_c = RobustScaler()
x_train_temp["metabolic_load_index"] = (
    scaler_g.fit_transform(x_train_temp[["glucose"]])
    + scaler_c.fit_transform(x_train_temp[["cholesterol"]])
).flatten()

# Baseline LightGBM 학습
baseline_model = lgb.LGBMRegressor(random_state=42, verbose=-1)
baseline_model.fit(x_train_temp, y_train)

# SHAP TreeExplainer 기여도 계산
explainer = shap.TreeExplainer(baseline_model)
shap_values = explainer.shap_values(x_train_temp)

if isinstance(shap_values, list):
    shap_avg = np.abs(shap_values[0]).mean(axis=0)
else:
    shap_avg = np.abs(shap_values).mean(axis=0)

shap_imp = pd.Series(shap_avg, index=x_train_temp.columns).sort_values(ascending=False)
print("\n--- SHAP Feature Importances (Absolute Mean) ---")
for feat, val in shap_imp.items():
    print(f"{feat}: {val:.6f}")

# summary_plot(bar) 출력 및 이미지 파일 저장
plt.figure(figsize=(10, 8))
shap.summary_plot(shap_values, x_train_temp, plot_type="bar", show=False)
plt.tight_layout()
output_dir = "result/v5" if os.path.exists("result/v5") else "."
os.makedirs(output_dir, exist_ok=True)
plt.savefig(os.path.join(output_dir, "shap_summary_plot.png"))
plt.close()
print(
    f"\nSHAP summary plot saved to {os.path.join(output_dir, 'shap_summary_plot.png')}"
)

# 최하위 N개 피처 자동 제거 (조절 변수 N = 3)
N = 3
features_to_drop = list(shap_imp.tail(N).index)
print(f"\nRemoving bottom {N} features from dataset: {features_to_drop}")

# x_train, x_test에서 제거
x_train = x_train.drop(
    columns=[f for f in features_to_drop if f in x_train.columns], errors="ignore"
)
x_test = x_test.drop(
    columns=[f for f in features_to_drop if f in x_test.columns], errors="ignore"
)
print(f"Pruned x_train shape: {x_train.shape}, pruned x_test shape: {x_test.shape}")

Calculating SHAP values for baseline model feature selection...

--- SHAP Feature Importances (Absolute Mean) ---
height: 0.024375
cholesterol: 0.019635
mean_working: 0.019056
glucose_cholesterol_ratio: 0.017066
bone_density: 0.016027
weight: 0.015968
bmi: 0.015723
glucose: 0.014892
metabolic_load_index: 0.014419
diastolic_blood_pressure: 0.014364
map: 0.013061
systolic_blood_pressure: 0.012020
age: 0.011295
pulse_pressure: 0.008592
smoke_status: 0.006865
sleep_pattern: 0.006599
edu_level_encoded: 0.006574
med_high_blood_pressure: 0.005248
activity_encoded: 0.003611
fam_high_blood_pressure: 0.002118
fam_heart_disease: 0.001357
med_heart_disease: 0.001117
med_diabetes: 0.001033
gender: 0.000730
fam_diabetes: 0.000713
is_working_missing: 0.000289
overwork_and_poor_sleep: 0.000000
vascular_bone_risk: 0.000000

SHAP summary plot saved to ./shap_summary_plot.png

Removing bottom 3 features from dataset: ['is_working_missing', 'overwork_and_poor_sleep', 'vascular_bone_risk']
Pruned x_train shape: (3000, 24), pruned x_test shape: (3000, 24)

In [14]:
import numpy as np
import pandas as pd
import lightgbm as lgb
import xgboost as xgb
from catboost import CatBoostRegressor
import optuna
from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import RobustScaler
from scipy.optimize import minimize
import warnings

warnings.filterwarnings("ignore")

# dynamic cat_features list based on remaining columns after SHAP pruning
cat_cols = [
    c for c in ["gender", "smoke_status", "sleep_pattern"] if c in x_train.columns
]
print(f"Categorical columns for CatBoost: {cat_cols}")


# 1. LightGBM 하이퍼파라미터 튜닝 (50 trials)
def tune_lgbm(x_train, y_train):
    def objective(trial):
        params = {
            "objective": "regression_l1",
            "metric": "mae",
            "random_state": 42,
            "verbose": -1,
            "n_jobs": 1,
            "n_estimators": trial.suggest_int("n_estimators", 200, 800),
            "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.1, log=True),
            "num_leaves": trial.suggest_int("num_leaves", 15, 127),
            "min_child_samples": trial.suggest_int("min_child_samples", 10, 50),
            "subsample": trial.suggest_float("subsample", 0.6, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
            "reg_alpha": trial.suggest_float("reg_alpha", 1e-3, 10.0, log=True),
            "reg_lambda": trial.suggest_float("reg_lambda", 1e-3, 10.0, log=True),
        }
        kf = KFold(n_splits=5, shuffle=True, random_state=42)
        mae_scores = []
        for train_idx, val_idx in kf.split(x_train, y_train):
            X_tr, y_tr = x_train.iloc[train_idx].copy(), y_train.iloc[train_idx]
            X_val, y_val = x_train.iloc[val_idx].copy(), y_train.iloc[val_idx]

            scaler_g = RobustScaler()
            scaler_c = RobustScaler()
            X_tr["metabolic_load_index"] = (
                scaler_g.fit_transform(X_tr[["glucose"]])
                + scaler_c.fit_transform(X_tr[["cholesterol"]])
            ).flatten()
            X_val["metabolic_load_index"] = (
                scaler_g.transform(X_val[["glucose"]])
                + scaler_c.transform(X_val[["cholesterol"]])
            ).flatten()

            model = lgb.LGBMRegressor(**params)
            model.fit(
                X_tr,
                y_tr,
                eval_set=[(X_val, y_val)],
                callbacks=[lgb.early_stopping(30, verbose=False)],
            )
            preds = model.predict(X_val)
            mae_scores.append(mean_absolute_error(y_val, preds))
        mean_mae = np.mean(mae_scores)
        print(f" => [LGBM] Trial {trial.number} Finished. Mean MAE: {mean_mae:.6f}")
        return mean_mae

    optuna.logging.set_verbosity(optuna.logging.INFO)
    study = optuna.create_study(direction="minimize")
    study.optimize(objective, n_trials=50)
    return study.best_params


# 2. XGBoost 하이퍼파라미터 튜닝 (30 trials)
def tune_xgboost(x_train, y_train):
    def objective(trial):
        params = {
            "objective": "reg:absoluteerror",
            "eval_metric": "mae",
            "random_state": 42,
            "verbosity": 0,
            "n_jobs": 1,
            "enable_categorical": True,
            "tree_method": "hist",
            "n_estimators": trial.suggest_int("n_estimators", 200, 800),
            "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.1, log=True),
            "max_depth": trial.suggest_int("max_depth", 3, 9),
            "min_child_weight": trial.suggest_int("min_child_weight", 1, 10),
            "subsample": trial.suggest_float("subsample", 0.6, 1.0),
            "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
            "alpha": trial.suggest_float("alpha", 1e-3, 10.0, log=True),
            "lambda": trial.suggest_float("lambda", 1e-3, 10.0, log=True),
        }
        kf = KFold(n_splits=5, shuffle=True, random_state=42)
        mae_scores = []
        for train_idx, val_idx in kf.split(x_train, y_train):
            X_tr, y_tr = x_train.iloc[train_idx].copy(), y_train.iloc[train_idx]
            X_val, y_val = x_train.iloc[val_idx].copy(), y_train.iloc[val_idx]

            scaler_g = RobustScaler()
            scaler_c = RobustScaler()
            X_tr["metabolic_load_index"] = (
                scaler_g.fit_transform(X_tr[["glucose"]])
                + scaler_c.fit_transform(X_tr[["cholesterol"]])
            ).flatten()
            X_val["metabolic_load_index"] = (
                scaler_g.transform(X_val[["glucose"]])
                + scaler_c.transform(X_val[["cholesterol"]])
            ).flatten()

            model = xgb.XGBRegressor(**params)
            model.fit(X_tr, y_tr, eval_set=[(X_val, y_val)], verbose=False)
            preds = model.predict(X_val)
            mae_scores.append(mean_absolute_error(y_val, preds))
        mean_mae = np.mean(mae_scores)
        print(f" => [XGBoost] Trial {trial.number} Finished. Mean MAE: {mean_mae:.6f}")
        return mean_mae

    import os

    optuna.logging.set_verbosity(optuna.logging.INFO)
    study = optuna.create_study(direction="minimize")
    study.optimize(objective, n_trials=50)
    return study.best_params


# 3. CatBoost 하이퍼파라미터 튜닝 (50 trials, depth 4~8 범위 확장, CPU 기반)
def tune_catboost(x_train, y_train):
    def objective(trial):
        params = {
            "loss_function": "MAE",
            "eval_metric": "MAE",
            "random_seed": 42,
            "verbose": False,
            "task_type": "CPU",
            "thread_count": 1,
            "n_estimators": trial.suggest_int("n_estimators", 200, 500),
            "learning_rate": trial.suggest_float("learning_rate", 0.01, 0.1, log=True),
            "depth": trial.suggest_int("depth", 4, 8),
            "l2_leaf_reg": trial.suggest_float("l2_leaf_reg", 1e-3, 10.0, log=True),
        }
        kf = KFold(n_splits=5, shuffle=True, random_state=42)
        mae_scores = []
        for train_idx, val_idx in kf.split(x_train, y_train):
            X_tr, y_tr = x_train.iloc[train_idx].copy(), y_train.iloc[train_idx]
            X_val, y_val = x_train.iloc[val_idx].copy(), y_train.iloc[val_idx]

            scaler_g = RobustScaler()
            scaler_c = RobustScaler()
            X_tr["metabolic_load_index"] = (
                scaler_g.fit_transform(X_tr[["glucose"]])
                + scaler_c.fit_transform(X_tr[["cholesterol"]])
            ).flatten()
            X_val["metabolic_load_index"] = (
                scaler_g.transform(X_val[["glucose"]])
                + scaler_c.transform(X_val[["cholesterol"]])
            ).flatten()

            model = CatBoostRegressor(**params)
            model.fit(
                X_tr,
                y_tr,
                eval_set=[(X_val, y_val)],
                cat_features=cat_cols,
                early_stopping_rounds=30,
                verbose=False,
            )
            preds = model.predict(X_val)
            mae_scores.append(mean_absolute_error(y_val, preds))
        mean_mae = np.mean(mae_scores)
        print(f" => [CatBoost] Trial {trial.number} Finished. Mean MAE: {mean_mae:.6f}")
        return mean_mae

    import os

    optuna.logging.set_verbosity(optuna.logging.INFO)
    study = optuna.create_study(direction="minimize")
    study.optimize(objective, n_trials=50)
    return study.best_params


print("Tuning LightGBM (50 trials)... ")
best_lgb = tune_lgbm(x_train, y_train)
print(f"Best LGBM Params: {best_lgb}")

print("Tuning XGBoost (50 trials)... ")
best_xgb = tune_xgboost(x_train, y_train)
print(f"Best XGBoost Params: {best_xgb}")

print("Tuning CatBoost (20 trials, depth 4-8)... ")
best_cat = tune_catboost(x_train, y_train)
print(f"Best CatBoost Params: {best_cat}")


# 4. Seed Averaging (Seeds: 42, 2026, 777) 최종 학습 수행 함수
def train_with_seeds(
    x_train, y_train, x_test, model_type, best_params, seeds=[42, 2026, 777]
):
    oof_preds = np.zeros(len(x_train))
    test_preds = np.zeros(len(x_test))
    kf = KFold(n_splits=5, shuffle=True, random_state=42)

    for fold, (train_idx, val_idx) in enumerate(kf.split(x_train, y_train)):
        X_tr, y_tr = x_train.iloc[train_idx].copy(), y_train.iloc[train_idx]
        X_val, y_val = x_train.iloc[val_idx].copy(), y_train.iloc[val_idx]

        scaler_g = RobustScaler()
        scaler_c = RobustScaler()
        X_tr["metabolic_load_index"] = (
            scaler_g.fit_transform(X_tr[["glucose"]])
            + scaler_c.fit_transform(X_tr[["cholesterol"]])
        ).flatten()
        X_val["metabolic_load_index"] = (
            scaler_g.transform(X_val[["glucose"]])
            + scaler_c.transform(X_val[["cholesterol"]])
        ).flatten()

        x_te_fold = x_test.copy()
        x_te_fold["metabolic_load_index"] = (
            scaler_g.transform(x_te_fold[["glucose"]])
            + scaler_c.transform(x_te_fold[["cholesterol"]])
        ).flatten()

        fold_val_preds = np.zeros(len(X_val))
        fold_test_preds = np.zeros(len(x_te_fold))

        for seed in seeds:
            if model_type == "lgb":
                params = best_params.copy()
                params.update(
                    {
                        "objective": "regression_l1",
                        "metric": "mae",
                        "random_state": seed,
                        "verbose": -1,
                        "n_jobs": 1,
                    }
                )
                model = lgb.LGBMRegressor(**params)
                model.fit(
                    X_tr,
                    y_tr,
                    eval_set=[(X_val, y_val)],
                    callbacks=[lgb.early_stopping(30, verbose=False)],
                )

            elif model_type == "xgb":
                params = best_params.copy()
                params.update(
                    {
                        "objective": "reg:absoluteerror",
                        "eval_metric": "mae",
                        "random_state": seed,
                        "verbosity": 0,
                        "enable_categorical": True,
                        "tree_method": "hist",
                        "n_jobs": 1,
                    }
                )
                model = xgb.XGBRegressor(**params)
                model.fit(X_tr, y_tr, eval_set=[(X_val, y_val)], verbose=False)

            elif model_type == "cat":
                params = best_params.copy()
                params.update(
                    {
                        "loss_function": "MAE",
                        "eval_metric": "MAE",
                        "random_seed": seed,
                        "verbose": False,
                        "task_type": "CPU",
                        "thread_count": 1,
                    }
                )
                model = CatBoostRegressor(**params)
                model.fit(
                    X_tr,
                    y_tr,
                    eval_set=[(X_val, y_val)],
                    cat_features=cat_cols,
                    early_stopping_rounds=30,
                    verbose=False,
                )

            fold_val_preds += model.predict(X_val) / len(seeds)
            fold_test_preds += model.predict(x_te_fold) / len(seeds)

        oof_preds[val_idx] = fold_val_preds
        test_preds += fold_test_preds / 5

    mae = mean_absolute_error(y_train, oof_preds)
    print(f"[{model_type.upper()}] Seed Averaged OOF MAE: {mae:.6f}")
    return oof_preds, test_preds


print("Training models with seed averaging...")
oof_lgb, test_lgb = train_with_seeds(x_train, y_train, x_test, "lgb", best_lgb)
oof_xgb, test_xgb = train_with_seeds(x_train, y_train, x_test, "xgb", best_xgb)
oof_cat, test_cat = train_with_seeds(x_train, y_train, x_test, "cat", best_cat)

# 5. SLSQP 가중치 최적화 블렌딩 (가중치 합 = 1.0, 0~1 바운드 설정)
oof_preds_list = [oof_lgb, oof_xgb, oof_cat]


def mae_objective(weights):
    w = weights / np.sum(weights)
    blended_pred = (
        (w[0] * oof_preds_list[0])
        + (w[1] * oof_preds_list[1])
        + (w[2] * oof_preds_list[2])
    )
    return mean_absolute_error(y_train, blended_pred)


constraints = {"type": "eq", "fun": lambda w: 1 - sum(w)}
bounds = [(0, 1), (0, 1), (0, 1)]
initial_weights = [1 / 3, 1 / 3, 1 / 3]

res = minimize(
    mae_objective,
    initial_weights,
    method="SLSQP",
    bounds=bounds,
    constraints=constraints,
)
best_weights = res.x / np.sum(res.x)

print(f"\nOptimal Blending Weights (LGB, XGB, CAT): {best_weights}")
blended_oof = (
    (best_weights[0] * oof_lgb)
    + (best_weights[1] * oof_xgb)
    + (best_weights[2] * oof_cat)
)

# Boundary Clipping 적용하여 안정성 보장
blended_oof_clipped = np.clip(blended_oof, 0.0, 1.0)
print(
    f"Final Blended Clipped OOF MAE: {mean_absolute_error(y_train, blended_oof_clipped):.6f}"
)

test_preds = (
    (best_weights[0] * test_lgb)
    + (best_weights[1] * test_xgb)
    + (best_weights[2] * test_cat)
)
test_preds = np.clip(test_preds, 0.0, 1.0)

[I 2026-06-16 23:39:06,530] A new study created in memory with name: no-name-76b3aedf-0de3-4056-834a-8d7c374f1aa5

Categorical columns for CatBoost: ['gender', 'smoke_status', 'sleep_pattern']
Tuning LightGBM (50 trials)...

[I 2026-06-16 23:39:09,685] Trial 0 finished with value: 0.2046555995587332 and parameters: {'n_estimators': 685, 'learning_rate': 0.07096711919878017, 'num_leaves': 91, 'min_child_samples': 37, 'subsample': 0.8340210824662058, 'colsample_bytree': 0.6682083212576182, 'reg_alpha': 4.378537806780758, 'reg_lambda': 5.278095350446253}. Best is trial 0 with value: 0.2046555995587332.

 => [LGBM] Trial 0 Finished. Mean MAE: 0.204656

[I 2026-06-16 23:39:13,441] Trial 1 finished with value: 0.20444268359367368 and parameters: {'n_estimators': 538, 'learning_rate': 0.015996863136873752, 'num_leaves': 64, 'min_child_samples': 18, 'subsample': 0.9252284672748562, 'colsample_bytree': 0.6616099609928862, 'reg_alpha': 0.07384641744540682, 'reg_lambda': 0.29170337728942997}. Best is trial 1 with value: 0.20444268359367368.

 => [LGBM] Trial 1 Finished. Mean MAE: 0.204443

[I 2026-06-16 23:39:15,780] Trial 2 finished with value: 0.22056028181137471 and parameters: {'n_estimators': 428, 'learning_rate': 0.01180353917998456, 'num_leaves': 93, 'min_child_samples': 42, 'subsample': 0.7643411832253953, 'colsample_bytree': 0.8475632612485039, 'reg_alpha': 0.22883156371768645, 'reg_lambda': 0.4470767119453457}. Best is trial 1 with value: 0.20444268359367368.

 => [LGBM] Trial 2 Finished. Mean MAE: 0.220560

[I 2026-06-16 23:39:23,222] Trial 3 finished with value: 0.19381057090826373 and parameters: {'n_estimators': 785, 'learning_rate': 0.02281003881955984, 'num_leaves': 95, 'min_child_samples': 18, 'subsample': 0.9414373324823991, 'colsample_bytree': 0.7946334389867177, 'reg_alpha': 0.304205601901306, 'reg_lambda': 0.5628670066288328}. Best is trial 3 with value: 0.19381057090826373.

 => [LGBM] Trial 3 Finished. Mean MAE: 0.193811

[I 2026-06-16 23:39:25,290] Trial 4 finished with value: 0.21439500824582036 and parameters: {'n_estimators': 561, 'learning_rate': 0.03795167896303927, 'num_leaves': 38, 'min_child_samples': 48, 'subsample': 0.9769500722294748, 'colsample_bytree': 0.6978528637598836, 'reg_alpha': 7.450091058308616, 'reg_lambda': 0.09103478198423506}. Best is trial 3 with value: 0.19381057090826373.

 => [LGBM] Trial 4 Finished. Mean MAE: 0.214395

[I 2026-06-16 23:39:30,093] Trial 5 finished with value: 0.20180305080033825 and parameters: {'n_estimators': 598, 'learning_rate': 0.022438676946009213, 'num_leaves': 123, 'min_child_samples': 26, 'subsample': 0.8356461139297756, 'colsample_bytree': 0.919535318356594, 'reg_alpha': 0.4325674757915891, 'reg_lambda': 0.07451602286312702}. Best is trial 3 with value: 0.19381057090826373.

 => [LGBM] Trial 5 Finished. Mean MAE: 0.201803

[I 2026-06-16 23:39:34,268] Trial 6 finished with value: 0.20674758157036624 and parameters: {'n_estimators': 743, 'learning_rate': 0.032603927237844464, 'num_leaves': 126, 'min_child_samples': 39, 'subsample': 0.9201982181797511, 'colsample_bytree': 0.9286277939854487, 'reg_alpha': 2.459891124196649, 'reg_lambda': 0.012166512522121876}. Best is trial 3 with value: 0.19381057090826373.

 => [LGBM] Trial 6 Finished. Mean MAE: 0.206748

[I 2026-06-16 23:39:40,451] Trial 7 finished with value: 0.18992859469677853 and parameters: {'n_estimators': 732, 'learning_rate': 0.04253433705253103, 'num_leaves': 69, 'min_child_samples': 11, 'subsample': 0.6399139634695482, 'colsample_bytree': 0.8987253300923214, 'reg_alpha': 0.010372627787148472, 'reg_lambda': 0.2732215574548917}. Best is trial 7 with value: 0.18992859469677853.

 => [LGBM] Trial 7 Finished. Mean MAE: 0.189929

[I 2026-06-16 23:39:43,398] Trial 8 finished with value: 0.2049011264730559 and parameters: {'n_estimators': 358, 'learning_rate': 0.02014716959400436, 'num_leaves': 102, 'min_child_samples': 22, 'subsample': 0.615513695404584, 'colsample_bytree': 0.7900998472855835, 'reg_alpha': 0.04046753117578715, 'reg_lambda': 2.7883356697905435}. Best is trial 7 with value: 0.18992859469677853.

 => [LGBM] Trial 8 Finished. Mean MAE: 0.204901

[I 2026-06-16 23:39:46,539] Trial 9 finished with value: 0.22132679210654654 and parameters: {'n_estimators': 724, 'learning_rate': 0.010094511507015392, 'num_leaves': 27, 'min_child_samples': 39, 'subsample': 0.8378731918752872, 'colsample_bytree': 0.8853757811718808, 'reg_alpha': 1.3899298124968238, 'reg_lambda': 0.03450508143436715}. Best is trial 7 with value: 0.18992859469677853.

 => [LGBM] Trial 9 Finished. Mean MAE: 0.221327

[I 2026-06-16 23:39:48,442] Trial 10 finished with value: 0.19596440248748123 and parameters: {'n_estimators': 269, 'learning_rate': 0.09452719978641372, 'num_leaves': 56, 'min_child_samples': 12, 'subsample': 0.6188485107854712, 'colsample_bytree': 0.9751174005667902, 'reg_alpha': 0.0011875876937667742, 'reg_lambda': 0.001461454334010653}. Best is trial 7 with value: 0.18992859469677853.

 => [LGBM] Trial 10 Finished. Mean MAE: 0.195964

[I 2026-06-16 23:39:54,998] Trial 11 finished with value: 0.1898222767096025 and parameters: {'n_estimators': 776, 'learning_rate': 0.04550913684685474, 'num_leaves': 72, 'min_child_samples': 11, 'subsample': 0.7035502601954684, 'colsample_bytree': 0.8120665035030139, 'reg_alpha': 0.007895030837137395, 'reg_lambda': 0.7697157102755301}. Best is trial 11 with value: 0.1898222767096025.

 => [LGBM] Trial 11 Finished. Mean MAE: 0.189822

[I 2026-06-16 23:40:00,292] Trial 12 finished with value: 0.1904861516893644 and parameters: {'n_estimators': 651, 'learning_rate': 0.04851410024377764, 'num_leaves': 68, 'min_child_samples': 11, 'subsample': 0.6885597533679456, 'colsample_bytree': 0.7649388561761501, 'reg_alpha': 0.004640788309515127, 'reg_lambda': 1.3615692022103132}. Best is trial 11 with value: 0.1898222767096025.

 => [LGBM] Trial 12 Finished. Mean MAE: 0.190486

[I 2026-06-16 23:40:07,367] Trial 13 finished with value: 0.18865297668398776 and parameters: {'n_estimators': 784, 'learning_rate': 0.054152792774970905, 'num_leaves': 74, 'min_child_samples': 10, 'subsample': 0.7034393239118345, 'colsample_bytree': 0.8434020866283302, 'reg_alpha': 0.011902840198918239, 'reg_lambda': 7.621542220004646}. Best is trial 13 with value: 0.18865297668398776.

 => [LGBM] Trial 13 Finished. Mean MAE: 0.188653

[I 2026-06-16 23:40:12,104] Trial 14 finished with value: 0.19947340848243886 and parameters: {'n_estimators': 778, 'learning_rate': 0.06055698404844742, 'num_leaves': 49, 'min_child_samples': 29, 'subsample': 0.7153014073049979, 'colsample_bytree': 0.8337773683043632, 'reg_alpha': 0.011107758296833654, 'reg_lambda': 8.41406907476434}. Best is trial 13 with value: 0.18865297668398776.

 => [LGBM] Trial 14 Finished. Mean MAE: 0.199473

[I 2026-06-16 23:40:17,265] Trial 15 finished with value: 0.1949769936382571 and parameters: {'n_estimators': 639, 'learning_rate': 0.030486203528312848, 'num_leaves': 77, 'min_child_samples': 16, 'subsample': 0.7519226919557106, 'colsample_bytree': 0.7365173310780456, 'reg_alpha': 0.0011385046665915556, 'reg_lambda': 2.0519753911925065}. Best is trial 13 with value: 0.18865297668398776.

 => [LGBM] Trial 15 Finished. Mean MAE: 0.194977

[I 2026-06-16 23:40:24,284] Trial 16 finished with value: 0.19095240876136074 and parameters: {'n_estimators': 800, 'learning_rate': 0.056265542238365246, 'num_leaves': 79, 'min_child_samples': 15, 'subsample': 0.6789614989580868, 'colsample_bytree': 0.8468440722538892, 'reg_alpha': 0.03870073309616601, 'reg_lambda': 8.80487663580868}. Best is trial 13 with value: 0.18865297668398776.

 => [LGBM] Trial 16 Finished. Mean MAE: 0.190952

[I 2026-06-16 23:40:27,684] Trial 17 finished with value: 0.19499480633271551 and parameters: {'n_estimators': 474, 'learning_rate': 0.08806017290136607, 'num_leaves': 105, 'min_child_samples': 22, 'subsample': 0.7734743773492361, 'colsample_bytree': 0.6141819308558729, 'reg_alpha': 0.00441080210069525, 'reg_lambda': 1.0387960508432916}. Best is trial 13 with value: 0.18865297668398776.

 => [LGBM] Trial 17 Finished. Mean MAE: 0.194995

[I 2026-06-16 23:40:31,378] Trial 18 finished with value: 0.20112620155675343 and parameters: {'n_estimators': 683, 'learning_rate': 0.07226830627953425, 'num_leaves': 45, 'min_child_samples': 29, 'subsample': 0.7257717380353533, 'colsample_bytree': 0.7349440462188963, 'reg_alpha': 0.012143709112103229, 'reg_lambda': 3.046828496150277}. Best is trial 13 with value: 0.18865297668398776.

 => [LGBM] Trial 18 Finished. Mean MAE: 0.201126

[I 2026-06-16 23:40:36,553] Trial 19 finished with value: 0.19681123559674102 and parameters: {'n_estimators': 609, 'learning_rate': 0.031274416511689614, 'num_leaves': 83, 'min_child_samples': 22, 'subsample': 0.6677199142873097, 'colsample_bytree': 0.9963527190281033, 'reg_alpha': 0.0029413323331795816, 'reg_lambda': 0.005231261990737837}. Best is trial 13 with value: 0.18865297668398776.

 => [LGBM] Trial 19 Finished. Mean MAE: 0.196811

[I 2026-06-16 23:40:39,056] Trial 20 finished with value: 0.20347966654363234 and parameters: {'n_estimators': 705, 'learning_rate': 0.04856772253475498, 'num_leaves': 25, 'min_child_samples': 10, 'subsample': 0.7922170839749701, 'colsample_bytree': 0.8149615313039634, 'reg_alpha': 0.0280588767369665, 'reg_lambda': 0.11946762808729153}. Best is trial 13 with value: 0.18865297668398776.

 => [LGBM] Trial 20 Finished. Mean MAE: 0.203480

[I 2026-06-16 23:40:45,059] Trial 21 finished with value: 0.1925063179661419 and parameters: {'n_estimators': 740, 'learning_rate': 0.04184052192811842, 'num_leaves': 66, 'min_child_samples': 14, 'subsample': 0.6445393297391174, 'colsample_bytree': 0.8827311818708111, 'reg_alpha': 0.012566488637685792, 'reg_lambda': 0.21871702784140185}. Best is trial 13 with value: 0.18865297668398776.

 => [LGBM] Trial 21 Finished. Mean MAE: 0.192506

[I 2026-06-16 23:40:52,098] Trial 22 finished with value: 0.18778987462296004 and parameters: {'n_estimators': 753, 'learning_rate': 0.04349176415066403, 'num_leaves': 75, 'min_child_samples': 10, 'subsample': 0.7061014818490011, 'colsample_bytree': 0.8809838705420564, 'reg_alpha': 0.008618711344555897, 'reg_lambda': 0.9546138721567047}. Best is trial 22 with value: 0.18778987462296004.

 => [LGBM] Trial 22 Finished. Mean MAE: 0.187790

[I 2026-06-16 23:40:58,601] Trial 23 finished with value: 0.18776422681052848 and parameters: {'n_estimators': 798, 'learning_rate': 0.05909033847593691, 'num_leaves': 58, 'min_child_samples': 10, 'subsample': 0.7096620266980338, 'colsample_bytree': 0.9493251035627486, 'reg_alpha': 0.09833798786577112, 'reg_lambda': 0.7827737630108184}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 23 Finished. Mean MAE: 0.187764

[I 2026-06-16 23:41:03,718] Trial 24 finished with value: 0.19460737255675475 and parameters: {'n_estimators': 669, 'learning_rate': 0.06233368578320939, 'num_leaves': 56, 'min_child_samples': 18, 'subsample': 0.7322704880279641, 'colsample_bytree': 0.9358505053745325, 'reg_alpha': 0.11131865270216815, 'reg_lambda': 3.493134609781485}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 24 Finished. Mean MAE: 0.194607

[I 2026-06-16 23:41:07,834] Trial 25 finished with value: 0.19518125834976843 and parameters: {'n_estimators': 800, 'learning_rate': 0.07600228839467141, 'num_leaves': 35, 'min_child_samples': 14, 'subsample': 0.8033294108449934, 'colsample_bytree': 0.9658071357305924, 'reg_alpha': 0.021195477160728116, 'reg_lambda': 1.2742605574022783}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 25 Finished. Mean MAE: 0.195181

[I 2026-06-16 23:41:09,426] Trial 26 finished with value: 0.20222807190641873 and parameters: {'n_estimators': 207, 'learning_rate': 0.05546088705641943, 'num_leaves': 56, 'min_child_samples': 14, 'subsample': 0.6633841914195896, 'colsample_bytree': 0.8594450240964742, 'reg_alpha': 0.10721883319628737, 'reg_lambda': 5.175929882630381}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 26 Finished. Mean MAE: 0.202228

[I 2026-06-16 23:41:17,042] Trial 27 finished with value: 0.18781734252314922 and parameters: {'n_estimators': 740, 'learning_rate': 0.03661489543771058, 'num_leaves': 82, 'min_child_samples': 10, 'subsample': 0.7284211877213096, 'colsample_bytree': 0.9470764609921287, 'reg_alpha': 0.6763306980495245, 'reg_lambda': 1.7494802174216535}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 27 Finished. Mean MAE: 0.187817

[I 2026-06-16 23:41:23,856] Trial 28 finished with value: 0.19645440797691696 and parameters: {'n_estimators': 739, 'learning_rate': 0.026194767436593835, 'num_leaves': 85, 'min_child_samples': 19, 'subsample': 0.7482475736553612, 'colsample_bytree': 0.9559272269413442, 'reg_alpha': 0.9932854496830095, 'reg_lambda': 0.5386154858703902}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 28 Finished. Mean MAE: 0.196454

[I 2026-06-16 23:41:31,715] Trial 29 finished with value: 0.1890115662311021 and parameters: {'n_estimators': 687, 'learning_rate': 0.036766533076000966, 'num_leaves': 102, 'min_child_samples': 13, 'subsample': 0.7964248568080894, 'colsample_bytree': 0.9938118712061375, 'reg_alpha': 0.6828800221681238, 'reg_lambda': 1.7569410328894657}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 29 Finished. Mean MAE: 0.189012

[I 2026-06-16 23:41:37,238] Trial 30 finished with value: 0.19098840505814482 and parameters: {'n_estimators': 623, 'learning_rate': 0.06721231467932451, 'num_leaves': 115, 'min_child_samples': 16, 'subsample': 0.8565463347293221, 'colsample_bytree': 0.9059475813926375, 'reg_alpha': 3.1981226477864872, 'reg_lambda': 0.03517634172068634}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 30 Finished. Mean MAE: 0.190988

[I 2026-06-16 23:41:44,899] Trial 31 finished with value: 0.18924285989484807 and parameters: {'n_estimators': 755, 'learning_rate': 0.05326088438152895, 'num_leaves': 87, 'min_child_samples': 11, 'subsample': 0.6936229234219429, 'colsample_bytree': 0.8708661900727422, 'reg_alpha': 0.1844538908900892, 'reg_lambda': 5.090176341077484}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 31 Finished. Mean MAE: 0.189243

[I 2026-06-16 23:41:50,883] Trial 32 finished with value: 0.19110131057887214 and parameters: {'n_estimators': 706, 'learning_rate': 0.036104321343042325, 'num_leaves': 62, 'min_child_samples': 10, 'subsample': 0.7260403176264306, 'colsample_bytree': 0.9628137066742665, 'reg_alpha': 0.05879238795863773, 'reg_lambda': 1.019006826947795}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 32 Finished. Mean MAE: 0.191101

[I 2026-06-16 23:41:57,360] Trial 33 finished with value: 0.19344693308056785 and parameters: {'n_estimators': 761, 'learning_rate': 0.08012639203908026, 'num_leaves': 76, 'min_child_samples': 20, 'subsample': 0.6508743086501825, 'colsample_bytree': 0.9352437239069842, 'reg_alpha': 0.022104151504197558, 'reg_lambda': 0.39885797594080985}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 33 Finished. Mean MAE: 0.193447

[I 2026-06-16 23:42:04,433] Trial 34 finished with value: 0.19312944820376807 and parameters: {'n_estimators': 704, 'learning_rate': 0.027022796982603927, 'num_leaves': 94, 'min_child_samples': 16, 'subsample': 0.7661673881888035, 'colsample_bytree': 0.9057984260972445, 'reg_alpha': 0.002701013842837198, 'reg_lambda': 0.18808171796301762}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 34 Finished. Mean MAE: 0.193129

[I 2026-06-16 23:42:08,731] Trial 35 finished with value: 0.19540917817392772 and parameters: {'n_estimators': 543, 'learning_rate': 0.03954930999914287, 'num_leaves': 61, 'min_child_samples': 13, 'subsample': 0.708640019637498, 'colsample_bytree': 0.8313571735810344, 'reg_alpha': 0.16817531344874484, 'reg_lambda': 0.6978746581754542}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 35 Finished. Mean MAE: 0.195409

[I 2026-06-16 23:42:14,300] Trial 36 finished with value: 0.19468038612358568 and parameters: {'n_estimators': 799, 'learning_rate': 0.050930166675122214, 'num_leaves': 48, 'min_child_samples': 10, 'subsample': 0.745452843121135, 'colsample_bytree': 0.869109762785397, 'reg_alpha': 0.3363544978503265, 'reg_lambda': 9.923644040923637}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 36 Finished. Mean MAE: 0.194680

[I 2026-06-16 23:42:17,094] Trial 37 finished with value: 0.21702347846594194 and parameters: {'n_estimators': 662, 'learning_rate': 0.017617652206315997, 'num_leaves': 90, 'min_child_samples': 47, 'subsample': 0.8749267482957874, 'colsample_bytree': 0.9448805005008981, 'reg_alpha': 7.3684108595155475, 'reg_lambda': 2.261826148049837}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 37 Finished. Mean MAE: 0.217023

[I 2026-06-16 23:42:18,697] Trial 38 finished with value: 0.21142997931212615 and parameters: {'n_estimators': 584, 'learning_rate': 0.06551289996631511, 'num_leaves': 15, 'min_child_samples': 16, 'subsample': 0.6005175704614942, 'colsample_bytree': 0.9246901452523146, 'reg_alpha': 0.5224271515352374, 'reg_lambda': 4.464128118419258}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 38 Finished. Mean MAE: 0.211430

[I 2026-06-16 23:42:25,474] Trial 39 finished with value: 0.19486002931546373 and parameters: {'n_estimators': 766, 'learning_rate': 0.03392121988934848, 'num_leaves': 75, 'min_child_samples': 18, 'subsample': 0.7777350652163112, 'colsample_bytree': 0.894631270352578, 'reg_alpha': 0.10981677206215526, 'reg_lambda': 1.694149428651514}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 39 Finished. Mean MAE: 0.194860

[I 2026-06-16 23:42:32,192] Trial 40 finished with value: 0.19087321927060102 and parameters: {'n_estimators': 721, 'learning_rate': 0.04374785986781039, 'num_leaves': 80, 'min_child_samples': 13, 'subsample': 0.686197496140636, 'colsample_bytree': 0.9133463666035866, 'reg_alpha': 1.5713531280001647, 'reg_lambda': 0.39950406379936243}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 40 Finished. Mean MAE: 0.190873

[I 2026-06-16 23:42:40,003] Trial 41 finished with value: 0.18900787381831977 and parameters: {'n_estimators': 688, 'learning_rate': 0.03759967286385973, 'num_leaves': 98, 'min_child_samples': 13, 'subsample': 0.8167188368556462, 'colsample_bytree': 0.9942735250956215, 'reg_alpha': 0.6206336240237569, 'reg_lambda': 1.7752338055189139}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 41 Finished. Mean MAE: 0.189008

[I 2026-06-16 23:42:48,791] Trial 42 finished with value: 0.18803792354724477 and parameters: {'n_estimators': 756, 'learning_rate': 0.02568194538332749, 'num_leaves': 114, 'min_child_samples': 12, 'subsample': 0.9636585068205076, 'colsample_bytree': 0.9780657403492895, 'reg_alpha': 0.7867068672963177, 'reg_lambda': 0.9769569142252489}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 42 Finished. Mean MAE: 0.188038

[I 2026-06-16 23:42:58,374] Trial 43 finished with value: 0.18974095618906345 and parameters: {'n_estimators': 758, 'learning_rate': 0.014896212743690714, 'num_leaves': 111, 'min_child_samples': 10, 'subsample': 0.9999270768582549, 'colsample_bytree': 0.9793875647408048, 'reg_alpha': 0.24700068345019724, 'reg_lambda': 0.7936032854060102}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 43 Finished. Mean MAE: 0.189741

[I 2026-06-16 23:43:06,378] Trial 44 finished with value: 0.18842834634688183 and parameters: {'n_estimators': 732, 'learning_rate': 0.027009519200464804, 'num_leaves': 120, 'min_child_samples': 12, 'subsample': 0.932401372170575, 'colsample_bytree': 0.9511239156185276, 'reg_alpha': 1.6207808829679746, 'reg_lambda': 0.350947648150898}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 44 Finished. Mean MAE: 0.188428

[I 2026-06-16 23:43:13,662] Trial 45 finished with value: 0.19061783615970837 and parameters: {'n_estimators': 718, 'learning_rate': 0.022976362759298125, 'num_leaves': 120, 'min_child_samples': 12, 'subsample': 0.9398688532421838, 'colsample_bytree': 0.9515255403719655, 'reg_alpha': 2.01277730048199, 'reg_lambda': 0.16890326856546095}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 45 Finished. Mean MAE: 0.190618

[I 2026-06-16 23:43:21,626] Trial 46 finished with value: 0.19105776335693164 and parameters: {'n_estimators': 739, 'learning_rate': 0.028251828900116526, 'num_leaves': 113, 'min_child_samples': 15, 'subsample': 0.9017261828621984, 'colsample_bytree': 0.9724163765606771, 'reg_alpha': 0.96506723987314, 'reg_lambda': 0.3075988237975043}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 46 Finished. Mean MAE: 0.191058

[I 2026-06-16 23:43:25,642] Trial 47 finished with value: 0.20269353474048932 and parameters: {'n_estimators': 635, 'learning_rate': 0.020969750667919285, 'num_leaves': 124, 'min_child_samples': 21, 'subsample': 0.9653505869214245, 'colsample_bytree': 0.9427170419942267, 'reg_alpha': 4.426286010324266, 'reg_lambda': 0.613228346164211}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 47 Finished. Mean MAE: 0.202694

[I 2026-06-16 23:43:33,842] Trial 48 finished with value: 0.19344967448672426 and parameters: {'n_estimators': 776, 'learning_rate': 0.02407675134697057, 'num_leaves': 119, 'min_child_samples': 17, 'subsample': 0.9039753935249467, 'colsample_bytree': 0.9216501122341046, 'reg_alpha': 0.3857973518350721, 'reg_lambda': 0.09556736237891245}. Best is trial 23 with value: 0.18776422681052848.

 => [LGBM] Trial 48 Finished. Mean MAE: 0.193450

[I 2026-06-16 23:43:39,188] Trial 49 finished with value: 0.20320381545991412 and parameters: {'n_estimators': 670, 'learning_rate': 0.01753125061169076, 'num_leaves': 109, 'min_child_samples': 26, 'subsample': 0.9640061397026793, 'colsample_bytree': 0.9822829137176403, 'reg_alpha': 0.9413332393961599, 'reg_lambda': 0.054697490627088875}. Best is trial 23 with value: 0.18776422681052848.
[I 2026-06-16 23:43:39,189] A new study created in memory with name: no-name-46ddbdde-f39c-414c-a28a-a7db132d87ec

 => [LGBM] Trial 49 Finished. Mean MAE: 0.203204
Best LGBM Params: {'n_estimators': 798, 'learning_rate': 0.05909033847593691, 'num_leaves': 58, 'min_child_samples': 10, 'subsample': 0.7096620266980338, 'colsample_bytree': 0.9493251035627486, 'reg_alpha': 0.09833798786577112, 'reg_lambda': 0.7827737630108184}
Tuning XGBoost (50 trials)...

[I 2026-06-16 23:43:40,241] Trial 0 finished with value: 0.2360071148431301 and parameters: {'n_estimators': 200, 'learning_rate': 0.014247325527567262, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.6774002614423769, 'colsample_bytree': 0.9954712122304233, 'alpha': 0.0011304104441963027, 'lambda': 0.011452193288676091}. Best is trial 0 with value: 0.2360071148431301.

 => [XGBoost] Trial 0 Finished. Mean MAE: 0.236007

[I 2026-06-16 23:43:45,500] Trial 1 finished with value: 0.2077737391857306 and parameters: {'n_estimators': 730, 'learning_rate': 0.017936590074470456, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.8623524516020168, 'colsample_bytree': 0.9023988614604253, 'alpha': 5.510228564461984, 'lambda': 0.7800410140124027}. Best is trial 1 with value: 0.2077737391857306.

 => [XGBoost] Trial 1 Finished. Mean MAE: 0.207774

[I 2026-06-16 23:43:49,015] Trial 2 finished with value: 0.2195651330073675 and parameters: {'n_estimators': 716, 'learning_rate': 0.01322916136779074, 'max_depth': 6, 'min_child_weight': 5, 'subsample': 0.6181634145659209, 'colsample_bytree': 0.7535339421501153, 'alpha': 0.0018991386374630388, 'lambda': 0.00197895636739558}. Best is trial 1 with value: 0.2077737391857306.

 => [XGBoost] Trial 2 Finished. Mean MAE: 0.219565

[I 2026-06-16 23:43:51,014] Trial 3 finished with value: 0.2344480487964551 and parameters: {'n_estimators': 568, 'learning_rate': 0.017060608668374996, 'max_depth': 3, 'min_child_weight': 8, 'subsample': 0.847327207435899, 'colsample_bytree': 0.9002962076470082, 'alpha': 2.844844350170774, 'lambda': 1.3475230400671565}. Best is trial 1 with value: 0.2077737391857306.

 => [XGBoost] Trial 3 Finished. Mean MAE: 0.234448

[I 2026-06-16 23:43:56,676] Trial 4 finished with value: 0.21515629200935366 and parameters: {'n_estimators': 547, 'learning_rate': 0.010136580888640112, 'max_depth': 8, 'min_child_weight': 1, 'subsample': 0.7910861364261041, 'colsample_bytree': 0.8841291807784184, 'alpha': 0.0023103323547994594, 'lambda': 0.036851276074693455}. Best is trial 1 with value: 0.2077737391857306.

 => [XGBoost] Trial 4 Finished. Mean MAE: 0.215156

[I 2026-06-16 23:43:58,455] Trial 5 finished with value: 0.2301617558525006 and parameters: {'n_estimators': 529, 'learning_rate': 0.04125832734254222, 'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.8914141555199886, 'colsample_bytree': 0.6813520243533021, 'alpha': 0.006278020796743532, 'lambda': 1.3171528143215423}. Best is trial 1 with value: 0.2077737391857306.

 => [XGBoost] Trial 5 Finished. Mean MAE: 0.230162

[I 2026-06-16 23:44:01,572] Trial 6 finished with value: 0.21312155544534322 and parameters: {'n_estimators': 531, 'learning_rate': 0.052558084668668945, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.9928477131333868, 'colsample_bytree': 0.8125919317946091, 'alpha': 0.18146084084161943, 'lambda': 0.004294411582227686}. Best is trial 1 with value: 0.2077737391857306.

 => [XGBoost] Trial 6 Finished. Mean MAE: 0.213122

[I 2026-06-16 23:44:04,128] Trial 7 finished with value: 0.23014494897941748 and parameters: {'n_estimators': 540, 'learning_rate': 0.01433047162590404, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.976103319042968, 'colsample_bytree': 0.9807770897788932, 'alpha': 2.6708429319121376, 'lambda': 1.6697280502933567}. Best is trial 1 with value: 0.2077737391857306.

 => [XGBoost] Trial 7 Finished. Mean MAE: 0.230145

[I 2026-06-16 23:44:07,948] Trial 8 finished with value: 0.19900225773006677 and parameters: {'n_estimators': 722, 'learning_rate': 0.0815419494018601, 'max_depth': 6, 'min_child_weight': 7, 'subsample': 0.7714942480037106, 'colsample_bytree': 0.6478841150384889, 'alpha': 2.3060904465832013, 'lambda': 0.0035585504583798746}. Best is trial 8 with value: 0.19900225773006677.

 => [XGBoost] Trial 8 Finished. Mean MAE: 0.199002

[I 2026-06-16 23:44:11,773] Trial 9 finished with value: 0.2028124447196722 and parameters: {'n_estimators': 585, 'learning_rate': 0.0425337182544626, 'max_depth': 7, 'min_child_weight': 5, 'subsample': 0.8041825296820313, 'colsample_bytree': 0.8424938243904664, 'alpha': 0.08108604554788637, 'lambda': 0.008892701498634806}. Best is trial 8 with value: 0.19900225773006677.

 => [XGBoost] Trial 9 Finished. Mean MAE: 0.202812

[I 2026-06-16 23:44:13,783] Trial 10 finished with value: 0.19804484273855885 and parameters: {'n_estimators': 256, 'learning_rate': 0.08879649245030706, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.7136487306206991, 'colsample_bytree': 0.6698912273475607, 'alpha': 0.2726232834398341, 'lambda': 0.11004583923430743}. Best is trial 10 with value: 0.19804484273855885.

 => [XGBoost] Trial 10 Finished. Mean MAE: 0.198045

[I 2026-06-16 23:44:15,621] Trial 11 finished with value: 0.19722260749677817 and parameters: {'n_estimators': 239, 'learning_rate': 0.0987257841044421, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.7218829828474254, 'colsample_bytree': 0.6156199126984611, 'alpha': 0.3809276877379454, 'lambda': 0.14979654243762056}. Best is trial 11 with value: 0.19722260749677817.

 => [XGBoost] Trial 11 Finished. Mean MAE: 0.197223

[I 2026-06-16 23:44:17,110] Trial 12 finished with value: 0.2018373245101174 and parameters: {'n_estimators': 214, 'learning_rate': 0.09317466641682326, 'max_depth': 9, 'min_child_weight': 10, 'subsample': 0.7104237668496405, 'colsample_bytree': 0.6140908344193361, 'alpha': 0.2717334493726483, 'lambda': 0.1053988719618124}. Best is trial 11 with value: 0.19722260749677817.

 => [XGBoost] Trial 12 Finished. Mean MAE: 0.201837

[I 2026-06-16 23:44:19,673] Trial 13 finished with value: 0.19831121264735857 and parameters: {'n_estimators': 324, 'learning_rate': 0.062008438052831134, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.7104702012694217, 'colsample_bytree': 0.7060721447016798, 'alpha': 0.028152218234373905, 'lambda': 0.18466156929890873}. Best is trial 11 with value: 0.19722260749677817.

 => [XGBoost] Trial 13 Finished. Mean MAE: 0.198311

[I 2026-06-16 23:44:22,091] Trial 14 finished with value: 0.19748518062616388 and parameters: {'n_estimators': 329, 'learning_rate': 0.09749098641369362, 'max_depth': 8, 'min_child_weight': 7, 'subsample': 0.6025022199753522, 'colsample_bytree': 0.6037058692001849, 'alpha': 0.6148407614361868, 'lambda': 6.128259032085688}. Best is trial 11 with value: 0.19722260749677817.

 => [XGBoost] Trial 14 Finished. Mean MAE: 0.197485

[I 2026-06-16 23:44:24,811] Trial 15 finished with value: 0.19685811032772063 and parameters: {'n_estimators': 360, 'learning_rate': 0.06669306505063471, 'max_depth': 8, 'min_child_weight': 6, 'subsample': 0.6374292696751771, 'colsample_bytree': 0.6065710738849027, 'alpha': 0.6040803043974216, 'lambda': 8.092499214689399}. Best is trial 15 with value: 0.19685811032772063.

 => [XGBoost] Trial 15 Finished. Mean MAE: 0.196858

[I 2026-06-16 23:44:28,261] Trial 16 finished with value: 0.20068381914436814 and parameters: {'n_estimators': 411, 'learning_rate': 0.03088569754224034, 'max_depth': 8, 'min_child_weight': 5, 'subsample': 0.6615946538185031, 'colsample_bytree': 0.7308329413034147, 'alpha': 0.04005704594616803, 'lambda': 5.033581994749481}. Best is trial 15 with value: 0.19685811032772063.

 => [XGBoost] Trial 16 Finished. Mean MAE: 0.200684

[I 2026-06-16 23:44:30,807] Trial 17 finished with value: 0.20011776820739113 and parameters: {'n_estimators': 428, 'learning_rate': 0.06601538978039038, 'max_depth': 7, 'min_child_weight': 6, 'subsample': 0.6409378869259436, 'colsample_bytree': 0.6412203327975616, 'alpha': 0.7377230601640853, 'lambda': 0.26066988923033135}. Best is trial 15 with value: 0.19685811032772063.

 => [XGBoost] Trial 17 Finished. Mean MAE: 0.200118

[I 2026-06-16 23:44:33,811] Trial 18 finished with value: 0.20446432700415454 and parameters: {'n_estimators': 316, 'learning_rate': 0.02822443351715572, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7512825066398594, 'colsample_bytree': 0.7696784617775364, 'alpha': 1.0238761396866893, 'lambda': 0.03441584939089064}. Best is trial 15 with value: 0.19685811032772063.

 => [XGBoost] Trial 18 Finished. Mean MAE: 0.204464

[I 2026-06-16 23:44:36,035] Trial 19 finished with value: 0.20408258022387823 and parameters: {'n_estimators': 407, 'learning_rate': 0.06794318417715818, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.6835229734199516, 'colsample_bytree': 0.6074225724795597, 'alpha': 0.012517103329304665, 'lambda': 0.3751374661443407}. Best is trial 15 with value: 0.19685811032772063.

 => [XGBoost] Trial 19 Finished. Mean MAE: 0.204083

[I 2026-06-16 23:44:40,618] Trial 20 finished with value: 0.19079824767231943 and parameters: {'n_estimators': 463, 'learning_rate': 0.051054863314037774, 'max_depth': 9, 'min_child_weight': 6, 'subsample': 0.7432878174932642, 'colsample_bytree': 0.7034963657813766, 'alpha': 0.11965520794864483, 'lambda': 8.599220784651596}. Best is trial 20 with value: 0.19079824767231943.

 => [XGBoost] Trial 20 Finished. Mean MAE: 0.190798

[I 2026-06-16 23:44:45,258] Trial 21 finished with value: 0.19007655365715423 and parameters: {'n_estimators': 459, 'learning_rate': 0.0492373020931904, 'max_depth': 9, 'min_child_weight': 6, 'subsample': 0.7457534531608193, 'colsample_bytree': 0.6990472169522125, 'alpha': 0.10911617983487372, 'lambda': 9.878583677965988}. Best is trial 21 with value: 0.19007655365715423.

 => [XGBoost] Trial 21 Finished. Mean MAE: 0.190077

[I 2026-06-16 23:44:50,003] Trial 22 finished with value: 0.18986633615156015 and parameters: {'n_estimators': 459, 'learning_rate': 0.04627392369305904, 'max_depth': 9, 'min_child_weight': 6, 'subsample': 0.8228373044421666, 'colsample_bytree': 0.7059181569786162, 'alpha': 0.11450714725663577, 'lambda': 9.79612643827911}. Best is trial 22 with value: 0.18986633615156015.

 => [XGBoost] Trial 22 Finished. Mean MAE: 0.189866

[I 2026-06-16 23:44:54,213] Trial 23 finished with value: 0.19416690327187378 and parameters: {'n_estimators': 459, 'learning_rate': 0.03958012609464249, 'max_depth': 9, 'min_child_weight': 6, 'subsample': 0.8205329599505964, 'colsample_bytree': 0.7162948404993016, 'alpha': 0.10888557587229919, 'lambda': 3.4728280665909828}. Best is trial 22 with value: 0.18986633615156015.

 => [XGBoost] Trial 23 Finished. Mean MAE: 0.194167

[I 2026-06-16 23:45:00,267] Trial 24 finished with value: 0.18953888792335988 and parameters: {'n_estimators': 475, 'learning_rate': 0.026828831710043334, 'max_depth': 9, 'min_child_weight': 4, 'subsample': 0.912730115368502, 'colsample_bytree': 0.7836635141294378, 'alpha': 0.05273881402555609, 'lambda': 9.974413555736621}. Best is trial 24 with value: 0.18953888792335988.

 => [XGBoost] Trial 24 Finished. Mean MAE: 0.189539

[I 2026-06-16 23:45:06,061] Trial 25 finished with value: 0.19872248286709188 and parameters: {'n_estimators': 624, 'learning_rate': 0.02469431920240395, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.932482911362692, 'colsample_bytree': 0.7910789147117714, 'alpha': 0.04749947454076146, 'lambda': 2.605614421563285}. Best is trial 24 with value: 0.18953888792335988.

 => [XGBoost] Trial 25 Finished. Mean MAE: 0.198722

[I 2026-06-16 23:45:12,405] Trial 26 finished with value: 0.1867968230019013 and parameters: {'n_estimators': 489, 'learning_rate': 0.03433457095630472, 'max_depth': 9, 'min_child_weight': 4, 'subsample': 0.9149802973124405, 'colsample_bytree': 0.744141825732314, 'alpha': 0.014611379155709791, 'lambda': 9.842427996525197}. Best is trial 26 with value: 0.1867968230019013.

 => [XGBoost] Trial 26 Finished. Mean MAE: 0.186797

[I 2026-06-16 23:45:17,060] Trial 27 finished with value: 0.20215361874928078 and parameters: {'n_estimators': 640, 'learning_rate': 0.03326699157475733, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.9215875021169126, 'colsample_bytree': 0.8299957264500906, 'alpha': 0.011947576493490417, 'lambda': 3.065316368069103}. Best is trial 26 with value: 0.1867968230019013.

 => [XGBoost] Trial 27 Finished. Mean MAE: 0.202154

[I 2026-06-16 23:45:21,838] Trial 28 finished with value: 0.20197666299174227 and parameters: {'n_estimators': 502, 'learning_rate': 0.022589685420891157, 'max_depth': 9, 'min_child_weight': 4, 'subsample': 0.9452690534492679, 'colsample_bytree': 0.7695480301519506, 'alpha': 0.01969336077935601, 'lambda': 0.5067953299682865}. Best is trial 26 with value: 0.1867968230019013.

 => [XGBoost] Trial 28 Finished. Mean MAE: 0.201977

[I 2026-06-16 23:45:25,438] Trial 29 finished with value: 0.198179609362185 and parameters: {'n_estimators': 371, 'learning_rate': 0.03612551598536275, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.8896803042565662, 'colsample_bytree': 0.738160708890909, 'alpha': 0.005689129137523984, 'lambda': 2.8563060872590444}. Best is trial 26 with value: 0.1867968230019013.

 => [XGBoost] Trial 29 Finished. Mean MAE: 0.198180

[I 2026-06-16 23:45:32,373] Trial 30 finished with value: 0.1900027198511362 and parameters: {'n_estimators': 493, 'learning_rate': 0.024338334654025778, 'max_depth': 9, 'min_child_weight': 2, 'subsample': 0.8949599814465472, 'colsample_bytree': 0.7947632073698314, 'alpha': 0.05755938578132839, 'lambda': 4.426800862880906}. Best is trial 26 with value: 0.1867968230019013.

 => [XGBoost] Trial 30 Finished. Mean MAE: 0.190003

[I 2026-06-16 23:45:39,273] Trial 31 finished with value: 0.1914736257666349 and parameters: {'n_estimators': 491, 'learning_rate': 0.023719731475043082, 'max_depth': 9, 'min_child_weight': 2, 'subsample': 0.8942707710111018, 'colsample_bytree': 0.7931069091386093, 'alpha': 0.05852110014333938, 'lambda': 4.4880794908983646}. Best is trial 26 with value: 0.1867968230019013.

 => [XGBoost] Trial 31 Finished. Mean MAE: 0.191474

[I 2026-06-16 23:45:47,359] Trial 32 finished with value: 0.19441973515604932 and parameters: {'n_estimators': 611, 'learning_rate': 0.02018112125003644, 'max_depth': 9, 'min_child_weight': 2, 'subsample': 0.8661378652696601, 'colsample_bytree': 0.8587194562841396, 'alpha': 0.02252835841376659, 'lambda': 1.8667945590803994}. Best is trial 26 with value: 0.1867968230019013.

 => [XGBoost] Trial 32 Finished. Mean MAE: 0.194420

[I 2026-06-16 23:45:51,509] Trial 33 finished with value: 0.2028065074423949 and parameters: {'n_estimators': 504, 'learning_rate': 0.031122451106784545, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.957256136964644, 'colsample_bytree': 0.7520542574734522, 'alpha': 0.008802218185407676, 'lambda': 0.8344143005341115}. Best is trial 26 with value: 0.1867968230019013.

 => [XGBoost] Trial 33 Finished. Mean MAE: 0.202807

[I 2026-06-16 23:46:01,909] Trial 34 finished with value: 0.18429228237410386 and parameters: {'n_estimators': 783, 'learning_rate': 0.02755379875484486, 'max_depth': 9, 'min_child_weight': 3, 'subsample': 0.8600388341085201, 'colsample_bytree': 0.7832183637681254, 'alpha': 0.03666353024273296, 'lambda': 6.238624840178506}. Best is trial 34 with value: 0.18429228237410386.

 => [XGBoost] Trial 34 Finished. Mean MAE: 0.184292

[I 2026-06-16 23:46:09,993] Trial 35 finished with value: 0.19038471632430948 and parameters: {'n_estimators': 786, 'learning_rate': 0.027732620323039706, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.8410955732575617, 'colsample_bytree': 0.7753480385714184, 'alpha': 0.003788234190896516, 'lambda': 6.084871658565138}. Best is trial 34 with value: 0.18429228237410386.

 => [XGBoost] Trial 35 Finished. Mean MAE: 0.190385

[I 2026-06-16 23:46:16,022] Trial 36 finished with value: 0.19966987449169157 and parameters: {'n_estimators': 677, 'learning_rate': 0.018049135702705287, 'max_depth': 9, 'min_child_weight': 5, 'subsample': 0.8583552354993068, 'colsample_bytree': 0.7400617121635193, 'alpha': 0.0010226577347810972, 'lambda': 0.9101060538354403}. Best is trial 34 with value: 0.18429228237410386.

 => [XGBoost] Trial 36 Finished. Mean MAE: 0.199670

[I 2026-06-16 23:46:22,892] Trial 37 finished with value: 0.19534259591360886 and parameters: {'n_estimators': 693, 'learning_rate': 0.03777689429077832, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.9149280781029426, 'colsample_bytree': 0.8144087174804642, 'alpha': 9.032947872849546, 'lambda': 9.125322180929913}. Best is trial 34 with value: 0.18429228237410386.

 => [XGBoost] Trial 37 Finished. Mean MAE: 0.195343

[I 2026-06-16 23:46:25,631] Trial 38 finished with value: 0.2137866528951128 and parameters: {'n_estimators': 586, 'learning_rate': 0.04579879237506159, 'max_depth': 5, 'min_child_weight': 5, 'subsample': 0.8309768880887686, 'colsample_bytree': 0.8656795347264907, 'alpha': 0.0023187769017559805, 'lambda': 1.8290224072726124}. Best is trial 34 with value: 0.18429228237410386.

 => [XGBoost] Trial 38 Finished. Mean MAE: 0.213787

[I 2026-06-16 23:46:35,139] Trial 39 finished with value: 0.19007621090307833 and parameters: {'n_estimators': 790, 'learning_rate': 0.02799251287824948, 'max_depth': 9, 'min_child_weight': 3, 'subsample': 0.8756326959012113, 'colsample_bytree': 0.9119051951305758, 'alpha': 0.027751941762894524, 'lambda': 1.1348182857167253}. Best is trial 34 with value: 0.18429228237410386.

 => [XGBoost] Trial 39 Finished. Mean MAE: 0.190076

[I 2026-06-16 23:46:41,234] Trial 40 finished with value: 0.18839094143817822 and parameters: {'n_estimators': 764, 'learning_rate': 0.05727817803204282, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.8051989463815262, 'colsample_bytree': 0.6735326488304557, 'alpha': 0.016031926504293432, 'lambda': 2.483842423687021}. Best is trial 34 with value: 0.18429228237410386.

 => [XGBoost] Trial 40 Finished. Mean MAE: 0.188391

[I 2026-06-16 23:46:47,768] Trial 41 finished with value: 0.18647142733469604 and parameters: {'n_estimators': 763, 'learning_rate': 0.05457494010968226, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.8111145385186583, 'colsample_bytree': 0.6777049137672192, 'alpha': 0.017182806298353375, 'lambda': 5.702846688227537}. Best is trial 34 with value: 0.18429228237410386.

 => [XGBoost] Trial 41 Finished. Mean MAE: 0.186471

[I 2026-06-16 23:46:52,946] Trial 42 finished with value: 0.1944109035674731 and parameters: {'n_estimators': 763, 'learning_rate': 0.05672175066123062, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.7894564685452791, 'colsample_bytree': 0.6712137626257768, 'alpha': 0.011551737656034629, 'lambda': 2.456508669124907}. Best is trial 34 with value: 0.18429228237410386.

 => [XGBoost] Trial 42 Finished. Mean MAE: 0.194411

[I 2026-06-16 23:46:59,305] Trial 43 finished with value: 0.18697698104387767 and parameters: {'n_estimators': 746, 'learning_rate': 0.07762689224984595, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.7888090185030308, 'colsample_bytree': 0.6484707914072645, 'alpha': 0.015352805460071036, 'lambda': 5.145792930695602}. Best is trial 34 with value: 0.18429228237410386.

 => [XGBoost] Trial 43 Finished. Mean MAE: 0.186977

[I 2026-06-16 23:47:04,117] Trial 44 finished with value: 0.19120969932263093 and parameters: {'n_estimators': 739, 'learning_rate': 0.0785589985554843, 'max_depth': 7, 'min_child_weight': 4, 'subsample': 0.7986066567946727, 'colsample_bytree': 0.6377499732606121, 'alpha': 0.004460751889495361, 'lambda': 4.025246731257157}. Best is trial 34 with value: 0.18429228237410386.

 => [XGBoost] Trial 44 Finished. Mean MAE: 0.191210

[I 2026-06-16 23:47:09,764] Trial 45 finished with value: 0.19053387230897945 and parameters: {'n_estimators': 758, 'learning_rate': 0.07507876392463836, 'max_depth': 8, 'min_child_weight': 5, 'subsample': 0.773898171699025, 'colsample_bytree': 0.6637362250568858, 'alpha': 0.017244193811191903, 'lambda': 1.4686344135555323}. Best is trial 34 with value: 0.18429228237410386.

 => [XGBoost] Trial 45 Finished. Mean MAE: 0.190534

[I 2026-06-16 23:47:16,037] Trial 46 finished with value: 0.1880846161123365 and parameters: {'n_estimators': 683, 'learning_rate': 0.05970032433854018, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.8082124469302493, 'colsample_bytree': 0.6903390372266794, 'alpha': 0.0029585111106561523, 'lambda': 6.3237424070036585}. Best is trial 34 with value: 0.18429228237410386.

 => [XGBoost] Trial 46 Finished. Mean MAE: 0.188085

[I 2026-06-16 23:47:20,813] Trial 47 finished with value: 0.1917818046371887 and parameters: {'n_estimators': 701, 'learning_rate': 0.07326731535697152, 'max_depth': 7, 'min_child_weight': 5, 'subsample': 0.8416904356260447, 'colsample_bytree': 0.6550331411336079, 'alpha': 0.008295525748116329, 'lambda': 5.74419384331379}. Best is trial 34 with value: 0.18429228237410386.

 => [XGBoost] Trial 47 Finished. Mean MAE: 0.191782

[I 2026-06-16 23:47:27,580] Trial 48 finished with value: 0.20466126554588474 and parameters: {'n_estimators': 734, 'learning_rate': 0.01062746067222701, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7753343418545077, 'colsample_bytree': 0.6840288247930746, 'alpha': 0.0015461440844748147, 'lambda': 6.135823334998198}. Best is trial 34 with value: 0.18429228237410386.

 => [XGBoost] Trial 48 Finished. Mean MAE: 0.204661

[I 2026-06-16 23:47:31,008] Trial 49 finished with value: 0.19811726625823106 and parameters: {'n_estimators': 664, 'learning_rate': 0.0874630845432242, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.8125347439384302, 'colsample_bytree': 0.6275233908201687, 'alpha': 0.003029576284073082, 'lambda': 0.0012275022729015088}. Best is trial 34 with value: 0.18429228237410386.
[I 2026-06-16 23:47:31,009] A new study created in memory with name: no-name-ec08329e-361e-4496-9fed-f21adc3a6ed5

 => [XGBoost] Trial 49 Finished. Mean MAE: 0.198117
Best XGBoost Params: {'n_estimators': 783, 'learning_rate': 0.02755379875484486, 'max_depth': 9, 'min_child_weight': 3, 'subsample': 0.8600388341085201, 'colsample_bytree': 0.7832183637681254, 'alpha': 0.03666353024273296, 'lambda': 6.238624840178506}
Tuning CatBoost (20 trials, depth 4-8)...

[I 2026-06-16 23:47:38,771] Trial 0 finished with value: 0.21991345313707722 and parameters: {'n_estimators': 292, 'learning_rate': 0.05277845677776629, 'depth': 7, 'l2_leaf_reg': 5.298201855327342}. Best is trial 0 with value: 0.21991345313707722.

 => [CatBoost] Trial 0 Finished. Mean MAE: 0.219913

[I 2026-06-16 23:47:42,626] Trial 1 finished with value: 0.2230362043214662 and parameters: {'n_estimators': 304, 'learning_rate': 0.0985199427031583, 'depth': 5, 'l2_leaf_reg': 0.03549293508534892}. Best is trial 0 with value: 0.21991345313707722.

 => [CatBoost] Trial 1 Finished. Mean MAE: 0.223036

[I 2026-06-16 23:47:46,167] Trial 2 finished with value: 0.23975545962760397 and parameters: {'n_estimators': 208, 'learning_rate': 0.015152618220499675, 'depth': 6, 'l2_leaf_reg': 0.042507588863228196}. Best is trial 0 with value: 0.21991345313707722.

 => [CatBoost] Trial 2 Finished. Mean MAE: 0.239755

[I 2026-06-16 23:47:54,253] Trial 3 finished with value: 0.21289049190885181 and parameters: {'n_estimators': 450, 'learning_rate': 0.0963242375533656, 'depth': 6, 'l2_leaf_reg': 2.8044555150345096}. Best is trial 3 with value: 0.21289049190885181.

 => [CatBoost] Trial 3 Finished. Mean MAE: 0.212890

[I 2026-06-16 23:47:56,648] Trial 4 finished with value: 0.23472900757955567 and parameters: {'n_estimators': 255, 'learning_rate': 0.05997864458865256, 'depth': 4, 'l2_leaf_reg': 0.7281824919776685}. Best is trial 3 with value: 0.21289049190885181.

 => [CatBoost] Trial 4 Finished. Mean MAE: 0.234729

[I 2026-06-16 23:48:07,339] Trial 5 finished with value: 0.21348183733163495 and parameters: {'n_estimators': 247, 'learning_rate': 0.06383220452504702, 'depth': 8, 'l2_leaf_reg': 9.667942732736924}. Best is trial 3 with value: 0.21289049190885181.

 => [CatBoost] Trial 5 Finished. Mean MAE: 0.213482

[I 2026-06-16 23:48:14,113] Trial 6 finished with value: 0.233952385676672 and parameters: {'n_estimators': 397, 'learning_rate': 0.01941065017833322, 'depth': 6, 'l2_leaf_reg': 0.008051048135936541}. Best is trial 3 with value: 0.21289049190885181.

 => [CatBoost] Trial 6 Finished. Mean MAE: 0.233952

[I 2026-06-16 23:48:18,264] Trial 7 finished with value: 0.22837033914767124 and parameters: {'n_estimators': 332, 'learning_rate': 0.053992875130823306, 'depth': 5, 'l2_leaf_reg': 0.0014002838531183312}. Best is trial 3 with value: 0.21289049190885181.

 => [CatBoost] Trial 7 Finished. Mean MAE: 0.228370

[I 2026-06-16 23:48:32,433] Trial 8 finished with value: 0.2095108043386275 and parameters: {'n_estimators': 327, 'learning_rate': 0.0597306579857173, 'depth': 8, 'l2_leaf_reg': 0.0021951060699242197}. Best is trial 8 with value: 0.2095108043386275.

 => [CatBoost] Trial 8 Finished. Mean MAE: 0.209511

[I 2026-06-16 23:48:35,863] Trial 9 finished with value: 0.23878817238414712 and parameters: {'n_estimators': 200, 'learning_rate': 0.017591567176591393, 'depth': 6, 'l2_leaf_reg': 0.23243125069762752}. Best is trial 8 with value: 0.2095108043386275.

 => [CatBoost] Trial 9 Finished. Mean MAE: 0.238788

[I 2026-06-16 23:48:57,255] Trial 10 finished with value: 0.21296791703885637 and parameters: {'n_estimators': 499, 'learning_rate': 0.029815479167828042, 'depth': 8, 'l2_leaf_reg': 0.0016816551770345825}. Best is trial 8 with value: 0.2095108043386275.

 => [CatBoost] Trial 10 Finished. Mean MAE: 0.212968

[I 2026-06-16 23:49:08,765] Trial 11 finished with value: 0.20821610771904098 and parameters: {'n_estimators': 428, 'learning_rate': 0.09931503520669532, 'depth': 7, 'l2_leaf_reg': 0.8370480986896747}. Best is trial 11 with value: 0.20821610771904098.

 => [CatBoost] Trial 11 Finished. Mean MAE: 0.208216

[I 2026-06-16 23:49:18,949] Trial 12 finished with value: 0.22203514133435537 and parameters: {'n_estimators': 384, 'learning_rate': 0.033378063517888065, 'depth': 7, 'l2_leaf_reg': 0.10339096956988644}. Best is trial 11 with value: 0.20821610771904098.

 => [CatBoost] Trial 12 Finished. Mean MAE: 0.222035

[I 2026-06-16 23:49:35,922] Trial 13 finished with value: 0.202821379346869 and parameters: {'n_estimators': 381, 'learning_rate': 0.08078698932477497, 'depth': 8, 'l2_leaf_reg': 0.012595650900647523}. Best is trial 13 with value: 0.202821379346869.

 => [CatBoost] Trial 13 Finished. Mean MAE: 0.202821

[I 2026-06-16 23:49:46,164] Trial 14 finished with value: 0.23510519372149527 and parameters: {'n_estimators': 407, 'learning_rate': 0.010373239253394126, 'depth': 7, 'l2_leaf_reg': 1.1324423251427138}. Best is trial 13 with value: 0.202821379346869.

 => [CatBoost] Trial 14 Finished. Mean MAE: 0.235105

[I 2026-06-16 23:49:58,231] Trial 15 finished with value: 0.20847184315205752 and parameters: {'n_estimators': 450, 'learning_rate': 0.07742711389981838, 'depth': 7, 'l2_leaf_reg': 0.009430758403151768}. Best is trial 13 with value: 0.202821379346869.

 => [CatBoost] Trial 15 Finished. Mean MAE: 0.208472

[I 2026-06-16 23:50:13,460] Trial 16 finished with value: 0.21416324931333106 and parameters: {'n_estimators': 359, 'learning_rate': 0.03833617689212307, 'depth': 8, 'l2_leaf_reg': 0.3589599316761497}. Best is trial 13 with value: 0.202821379346869.

 => [CatBoost] Trial 16 Finished. Mean MAE: 0.214163

[I 2026-06-16 23:50:25,194] Trial 17 finished with value: 0.20961571052394462 and parameters: {'n_estimators': 439, 'learning_rate': 0.08457567353997074, 'depth': 7, 'l2_leaf_reg': 0.018599364075086534}. Best is trial 13 with value: 0.202821379346869.

 => [CatBoost] Trial 17 Finished. Mean MAE: 0.209616

[I 2026-06-16 23:50:46,284] Trial 18 finished with value: 0.20641322622680022 and parameters: {'n_estimators': 492, 'learning_rate': 0.04352231837586097, 'depth': 8, 'l2_leaf_reg': 0.09344977578929699}. Best is trial 13 with value: 0.202821379346869.

 => [CatBoost] Trial 18 Finished. Mean MAE: 0.206413

[I 2026-06-16 23:51:07,793] Trial 19 finished with value: 0.20697663282496462 and parameters: {'n_estimators': 500, 'learning_rate': 0.04359731616936494, 'depth': 8, 'l2_leaf_reg': 0.005068974422244335}. Best is trial 13 with value: 0.202821379346869.

 => [CatBoost] Trial 19 Finished. Mean MAE: 0.206977

[I 2026-06-16 23:51:27,594] Trial 20 finished with value: 0.21670486701826724 and parameters: {'n_estimators': 467, 'learning_rate': 0.026034730065260952, 'depth': 8, 'l2_leaf_reg': 0.09450630149740323}. Best is trial 13 with value: 0.202821379346869.

 => [CatBoost] Trial 20 Finished. Mean MAE: 0.216705

[I 2026-06-16 23:51:48,799] Trial 21 finished with value: 0.2077632334931015 and parameters: {'n_estimators': 489, 'learning_rate': 0.0405994330002772, 'depth': 8, 'l2_leaf_reg': 0.0048253449186278375}. Best is trial 13 with value: 0.202821379346869.

 => [CatBoost] Trial 21 Finished. Mean MAE: 0.207763

[I 2026-06-16 23:52:09,521] Trial 22 finished with value: 0.20777914204750408 and parameters: {'n_estimators': 475, 'learning_rate': 0.043254985741614446, 'depth': 8, 'l2_leaf_reg': 0.004419648447423432}. Best is trial 13 with value: 0.202821379346869.

 => [CatBoost] Trial 22 Finished. Mean MAE: 0.207779

[I 2026-06-16 23:52:31,241] Trial 23 finished with value: 0.2067096172561139 and parameters: {'n_estimators': 500, 'learning_rate': 0.04695867824461079, 'depth': 8, 'l2_leaf_reg': 0.019269196702489257}. Best is trial 13 with value: 0.202821379346869.

 => [CatBoost] Trial 23 Finished. Mean MAE: 0.206710

[I 2026-06-16 23:52:47,119] Trial 24 finished with value: 0.205520996200402 and parameters: {'n_estimators': 366, 'learning_rate': 0.07280465594508184, 'depth': 8, 'l2_leaf_reg': 0.022945774167745868}. Best is trial 13 with value: 0.202821379346869.

 => [CatBoost] Trial 24 Finished. Mean MAE: 0.205521

[I 2026-06-16 23:52:56,967] Trial 25 finished with value: 0.21196280042281684 and parameters: {'n_estimators': 369, 'learning_rate': 0.07136457362301413, 'depth': 7, 'l2_leaf_reg': 0.07850661620177912}. Best is trial 13 with value: 0.202821379346869.

 => [CatBoost] Trial 25 Finished. Mean MAE: 0.211963

[I 2026-06-16 23:53:11,793] Trial 26 finished with value: 0.20623068223780439 and parameters: {'n_estimators': 341, 'learning_rate': 0.07254708144774627, 'depth': 8, 'l2_leaf_reg': 0.02527372385740494}. Best is trial 13 with value: 0.202821379346869.

 => [CatBoost] Trial 26 Finished. Mean MAE: 0.206231

[I 2026-06-16 23:53:21,113] Trial 27 finished with value: 0.21252253677022082 and parameters: {'n_estimators': 346, 'learning_rate': 0.07284107749360735, 'depth': 7, 'l2_leaf_reg': 0.01806637540622862}. Best is trial 13 with value: 0.202821379346869.

 => [CatBoost] Trial 27 Finished. Mean MAE: 0.212523

[I 2026-06-16 23:53:39,391] Trial 28 finished with value: 0.20055860275028542 and parameters: {'n_estimators': 417, 'learning_rate': 0.08445778528578697, 'depth': 8, 'l2_leaf_reg': 0.03549347322433179}. Best is trial 28 with value: 0.20055860275028542.

 => [CatBoost] Trial 28 Finished. Mean MAE: 0.200559

[I 2026-06-16 23:54:54,768] Trial 29 finished with value: 0.20023509081430618 and parameters: {'n_estimators': 415, 'learning_rate': 0.08390537877369632, 'depth': 8, 'l2_leaf_reg': 0.010415079656811519}. Best is trial 29 with value: 0.20023509081430618.

 => [CatBoost] Trial 29 Finished. Mean MAE: 0.200235

[I 2026-06-16 23:55:05,865] Trial 30 finished with value: 0.20812485461095137 and parameters: {'n_estimators': 417, 'learning_rate': 0.08161046706418128, 'depth': 7, 'l2_leaf_reg': 0.008755429949899382}. Best is trial 29 with value: 0.20023509081430618.

 => [CatBoost] Trial 30 Finished. Mean MAE: 0.208125

[I 2026-06-16 23:55:22,672] Trial 31 finished with value: 0.20801719533577154 and parameters: {'n_estimators': 388, 'learning_rate': 0.05327054465231073, 'depth': 8, 'l2_leaf_reg': 0.05123886904915242}. Best is trial 29 with value: 0.20023509081430618.

 => [CatBoost] Trial 31 Finished. Mean MAE: 0.208017

[I 2026-06-16 23:55:38,768] Trial 32 finished with value: 0.20145203701469275 and parameters: {'n_estimators': 369, 'learning_rate': 0.08654464984066632, 'depth': 8, 'l2_leaf_reg': 0.18775419738087604}. Best is trial 29 with value: 0.20023509081430618.

 => [CatBoost] Trial 32 Finished. Mean MAE: 0.201452

[I 2026-06-16 23:55:57,034] Trial 33 finished with value: 0.20107436812451115 and parameters: {'n_estimators': 416, 'learning_rate': 0.08847857102408944, 'depth': 8, 'l2_leaf_reg': 0.2210342000331371}. Best is trial 29 with value: 0.20023509081430618.

 => [CatBoost] Trial 33 Finished. Mean MAE: 0.201074

[I 2026-06-16 23:56:15,452] Trial 34 finished with value: 0.19889883550300702 and parameters: {'n_estimators': 421, 'learning_rate': 0.08797109509139464, 'depth': 8, 'l2_leaf_reg': 0.327906401449503}. Best is trial 34 with value: 0.19889883550300702.

 => [CatBoost] Trial 34 Finished. Mean MAE: 0.198899

[I 2026-06-16 23:56:26,675] Trial 35 finished with value: 0.20663240161058055 and parameters: {'n_estimators': 418, 'learning_rate': 0.09431331716265322, 'depth': 7, 'l2_leaf_reg': 0.41807141612369875}. Best is trial 34 with value: 0.19889883550300702.

 => [CatBoost] Trial 35 Finished. Mean MAE: 0.206632

[I 2026-06-16 23:56:46,062] Trial 36 finished with value: 0.203704287660443 and parameters: {'n_estimators': 448, 'learning_rate': 0.06337865062250836, 'depth': 8, 'l2_leaf_reg': 1.821591659123184}. Best is trial 34 with value: 0.19889883550300702.

 => [CatBoost] Trial 36 Finished. Mean MAE: 0.203704

[I 2026-06-16 23:56:50,367] Trial 37 finished with value: 0.22627344972961883 and parameters: {'n_estimators': 466, 'learning_rate': 0.09062427709751028, 'depth': 4, 'l2_leaf_reg': 0.047413723453602626}. Best is trial 34 with value: 0.19889883550300702.

 => [CatBoost] Trial 37 Finished. Mean MAE: 0.226273

[I 2026-06-16 23:57:01,190] Trial 38 finished with value: 0.21322261330987224 and parameters: {'n_estimators': 405, 'learning_rate': 0.06416759246432141, 'depth': 7, 'l2_leaf_reg': 0.17363011622512375}. Best is trial 34 with value: 0.19889883550300702.

 => [CatBoost] Trial 38 Finished. Mean MAE: 0.213223

[I 2026-06-16 23:57:20,126] Trial 39 finished with value: 0.19794928503997503 and parameters: {'n_estimators': 434, 'learning_rate': 0.09882703226121584, 'depth': 8, 'l2_leaf_reg': 4.189369208778821}. Best is trial 39 with value: 0.19794928503997503.

 => [CatBoost] Trial 39 Finished. Mean MAE: 0.197949

[I 2026-06-16 23:57:25,698] Trial 40 finished with value: 0.21680653668048597 and parameters: {'n_estimators': 308, 'learning_rate': 0.09959385230601926, 'depth': 6, 'l2_leaf_reg': 4.985410667419954}. Best is trial 39 with value: 0.19794928503997503.

 => [CatBoost] Trial 40 Finished. Mean MAE: 0.216807

[I 2026-06-16 23:57:44,683] Trial 41 finished with value: 0.198005549507916 and parameters: {'n_estimators': 433, 'learning_rate': 0.0882032689496652, 'depth': 8, 'l2_leaf_reg': 7.3887622819467165}. Best is trial 39 with value: 0.19794928503997503.

 => [CatBoost] Trial 41 Finished. Mean MAE: 0.198006

[I 2026-06-16 23:58:03,703] Trial 42 finished with value: 0.20177536983568442 and parameters: {'n_estimators': 436, 'learning_rate': 0.06747134541369644, 'depth': 8, 'l2_leaf_reg': 7.572817652341425}. Best is trial 39 with value: 0.19794928503997503.

 => [CatBoost] Trial 42 Finished. Mean MAE: 0.201775

[I 2026-06-16 23:58:22,449] Trial 43 finished with value: 0.203909634671106 and parameters: {'n_estimators': 428, 'learning_rate': 0.05912681720863266, 'depth': 8, 'l2_leaf_reg': 3.678156396836015}. Best is trial 39 with value: 0.19794928503997503.

 => [CatBoost] Trial 43 Finished. Mean MAE: 0.203910

[I 2026-06-16 23:58:42,536] Trial 44 finished with value: 0.20001423404277566 and parameters: {'n_estimators': 460, 'learning_rate': 0.08015165159612367, 'depth': 8, 'l2_leaf_reg': 2.2660238763566904}. Best is trial 39 with value: 0.19794928503997503.

 => [CatBoost] Trial 44 Finished. Mean MAE: 0.200014

[I 2026-06-16 23:59:02,653] Trial 45 finished with value: 0.19659186072457208 and parameters: {'n_estimators': 457, 'learning_rate': 0.09970299844072499, 'depth': 8, 'l2_leaf_reg': 2.143924708150273}. Best is trial 45 with value: 0.19659186072457208.

 => [CatBoost] Trial 45 Finished. Mean MAE: 0.196592

[I 2026-06-16 23:59:08,528] Trial 46 finished with value: 0.220148976532395 and parameters: {'n_estimators': 461, 'learning_rate': 0.09960290966497895, 'depth': 5, 'l2_leaf_reg': 2.2189866409214685}. Best is trial 45 with value: 0.19659186072457208.

 => [CatBoost] Trial 46 Finished. Mean MAE: 0.220149

[I 2026-06-16 23:59:21,345] Trial 47 finished with value: 0.2107404797893587 and parameters: {'n_estimators': 477, 'learning_rate': 0.05762418687905802, 'depth': 7, 'l2_leaf_reg': 1.3598201196302482}. Best is trial 45 with value: 0.19659186072457208.

 => [CatBoost] Trial 47 Finished. Mean MAE: 0.210740

[I 2026-06-16 23:59:31,453] Trial 48 finished with value: 0.21061712040253852 and parameters: {'n_estimators': 234, 'learning_rate': 0.07618054008021861, 'depth': 8, 'l2_leaf_reg': 9.74882730141735}. Best is trial 45 with value: 0.19659186072457208.

 => [CatBoost] Trial 48 Finished. Mean MAE: 0.210617

[I 2026-06-16 23:59:50,986] Trial 49 finished with value: 0.1987189967012039 and parameters: {'n_estimators': 442, 'learning_rate': 0.0905919645487142, 'depth': 8, 'l2_leaf_reg': 3.6145706200135446}. Best is trial 45 with value: 0.19659186072457208.

 => [CatBoost] Trial 49 Finished. Mean MAE: 0.198719
Best CatBoost Params: {'n_estimators': 457, 'learning_rate': 0.09970299844072499, 'depth': 8, 'l2_leaf_reg': 2.143924708150273}
Training models with seed averaging...
[LGB] Seed Averaged OOF MAE: 0.187384
[XGB] Seed Averaged OOF MAE: 0.183198
[CAT] Seed Averaged OOF MAE: 0.194975

Optimal Blending Weights (LGB, XGB, CAT): [1.80411242e-16 1.00000000e+00 4.51028104e-17]
Final Blended Clipped OOF MAE: 0.183198

In [15]:
submission = pd.read_csv(os.path.join(data_dir, "sample_submission.csv"))

In [16]:
submission["stress_score"] = test_preds
submission.head()

          ID  stress_score
0  TEST_0000      0.530798
1  TEST_0001      0.742491
2  TEST_0002      0.351858
3  TEST_0003      0.428040
4  TEST_0004      0.569445

In [17]:
# 결과 저장 경로 자동 대응
output_dir = "result/v5" if os.path.exists("result/v5") else "."
submission.to_csv(os.path.join(output_dir, "submit_05.csv"), index=False)